import streamlit as st
import yfinance as yf
import pandas as pd
import time

# إعداد واجهة المستخدم
st.set_page_config(page_title="Radar Salman Al-Shaml", layout="wide")
st.title("🚀 Radar Salman Al-Shaml")

# القائمة الجانبية للإعدادات
st.sidebar.header("إعدادات الفلترة")
market_choice = st.sidebar.selectbox("اختر السوق", ["S&P 500", "Nasdaq 100"])
min_price = st.sidebar.number_input("أقل سعر للسهم ($)", value=10.0, step=1.0)
min_volume = st.sidebar.number_input("أقل حجم تداول (Volume)", value=1000000, step=50000)
refresh_rate = st.sidebar.slider("سرعة التحديث (بالثواني)", 10, 60, 30)

# دوال جلب القوائم
def get_tickers(market):
    if market == "S&P 500":
            return pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')[0]['Symbol'].tolist()
                else:
                        return pd.read_html('https://en.wikipedia.org/wiki/Nasdaq-100')[4]['Ticker'].tolist()

                        def get_data():
                            tickers = get_tickers(market_choice)
                                # تنظيف الرموز التي تحتوي على نقطة لـ yfinance
                                    tickers = [t.replace('.', '-') for t in tickers]
                                        
                                            results = []
                                                progress_bar = st.progress(0)
                                                    
                                                        st.write(f"🔍 جاري فحص {len(tickers)} سهم في سوق {market_choice}...")
                                                            
                                                                for i, ticker in enumerate(tickers):
                                                                        try:
                                                                                    # جلب بيانات اللحظية (دقيقة) وبيانات اليوم
                                                                                                stock = yf.Ticker(ticker)
                                                                                                            hist_1m = stock.history(period="1d", interval="1m")
                                                                                                                        hist_1h = stock.history(period="2d", interval="1h")
                                                                                                                                    hist_1d = stock.history(period="5d", interval="1d")
                                                                                                                                                
                                                                                                                                                            if hist_1m.empty or len(hist_1m) < 2:
                                                                                                                                                                            continue

                                                                                                                                                                                        current_price = hist_1m['Close'].iloc[-1]
                                                                                                                                                                                                    volume = hist_1m['Volume'].sum() # إجمالي حجم تداول اليوم

                                                                                                                                                                                                                # تطبيق فلاتر السعر والسيولة
                                                                                                                                                                                                                            if current_price < min_price or volume < min_volume:
                                                                                                                                                                                                                                            continue

                                                                                                                                                                                                                                                        # حساب نسب التغير (نفس شروطك)
                                                                                                                                                                                                                                                                    change_1m = ((current_price - hist_1m['Close'].iloc[-2]) / hist_1m['Close'].iloc[-2]) * 100
                                                                                                                                                                                                                                                                                change_5m = ((current_price - hist_1m['Close'].iloc[-6]) / hist_1m['Close'].iloc[-6]) * 100 if len(hist_1m) >= 6 else 0
                                                                                                                                                                                                                                                                                            change_15m = ((current_price - hist_1m['Close'].iloc[-16]) / hist_1m['Close'].iloc[-16]) * 100 if len(hist_1m) >= 16 else 0
                                                                                                                                                                                                                                                                                                        change_30m = ((current_price - hist_1m['Close'].iloc[-31]) / hist_1m['Close'].iloc[-31]) * 100 if len(hist_1m) >= 31 else 0
                                                                                                                                                                                                                                                                                                                    change_1h = ((current_price - hist_1h['Close'].iloc[-2]) / hist_1h['Close'].iloc[-2]) * 100 if len(hist_1h) >= 2 else 0
                                                                                                                                                                                                                                                                                                                                change_1d = ((current_price - hist_1d['Close'].iloc[-2]) / hist_1d['Close'].iloc[-2]) * 100 if len(hist_1d) >= 2 else 0

                                                                                                                                                                                                                                                                                                                                            results.append({
                                                                                                                                                                                                                                                                                                                                                            "Ticker": ticker,
                                                                                                                                                                                                                                                                                                                                                                            "Price": round(current_price, 2),
                                                                                                                                                                                                                                                                                                                                                                                            "Vol (Daily)": f"{volume:,}",
                                                                                                                                                                                                                                                                                                                                                                                                            "1m %": round(change_1m, 2),
                                                                                                                                                                                                                                                                                                                                                                                                                            "5m %": round(change_5m, 2),
                                                                                                                                                                                                                                                                                                                                                                                                                                            "15m %": round(change_15m, 2),
                                                                                                                                                                                                                                                                                                                                                                                                                                                            "30m %": round(change_30m, 2),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "1h %": round(change_1h, 2),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Daily %": round(change_1d, 2)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            except Exception:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        continue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            progress_bar.progress((i + 1) / len(tickers))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return pd.DataFrame(results)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # تشغيل الرادار
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    data_df = get_data()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if not data_df.empty:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        st.success(f"تم العثور على {len(data_df)} أسهم تطابق الشروط")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # عرض الجدول مع تلوين النسب (أخضر للموجب وأحمر للسالب)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.dataframe(data_df.sort_values(by="5m %", ascending=False).style.format(precision=2))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.warning("لا توجد أسهم تطابق الشروط حالياً. جرب تقليل السعر أو حجم التداول.")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # إعادة التحديث التلقائي
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    time.sleep(refresh_rate)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.rerun()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    